server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/summertrainingproject
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  #邮箱服务器
  mail:
    host: smtp.qq.com
    port: 587
    username: 3302821496@qq.com
    password: uyiesfeazkdocjeh
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            enable: false