# 应用服务 WEB 访问端口
server:
  port: 9090
spring:
  datasource:
    url: jdbc:mysql://192.168.1.54:3306/summertrainingproject?characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: zdk
    password: 20040722

