# 应用服务 WEB 访问端口
server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://192.168.1.54:3306/summertrainingproject
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: jly
    password: mysql

